### ISSUE TITLE
Problem with new svoboda dataset

### ISSUE THREAD

**Issue by yger** [flatironinstitute/neuropixels-data-sep-2020#21]
I just noticed the new dataset from svoboda's lab, and wanted to download them. While svoboda-SC022_030319_g0_tcat_imec2 is on its way, slowly, svoboda-SC035_011020_g0_tcat_imec0 crash quickly with the following error

kachery_p2p.exceptions.LoadFileError: Error loading file: File not found.: sha1://218e5e94898605086b99828f65359e5c23def8b6?chunkOf=ec1543ce5b040e5e56901859bf208b6f0afa4bb0~20000000~40000000

Moreover, while trying to download SC026_080619_g0_tcat_imec0, looks like it is using already cached data from scratch, so I'm suspecting there could again be a mixup between this file and SC022_030319_g0_tcat_imec2. Could it be ?

**Comment by yger** [comment]
First problem solved itself, since that connections are unstable, but working from times to times.

**Comment by magland** [comment]
Those svoboda datasets were not loaded onto my public-TCP-port server. And I just started downloading 035 there a few minutes ago, so that's probably what solved that.

I don't see any obvious mixup in the files. You can take a look at this preparation file to see if you see anything.

I will continue to load the svoboda datasets onto the public node -- please let me know how it goes.

**Comment by magland** [comment]
Oops forgot to paste link to preparation file for svoboda: https://github.com/flatironinstitute/neuropixels-data-sep-2020/blob/master/neuropixels_data_sep_2020/prepare_datasets/prepare_svoboda_datasets.py
